/* Mock product + content data. */

window.TAPI_DATA = (function () {
  // Weave pattern keys map to CSS background patterns in FabricSwatch.
  const PRODUCTS = [
    {
      id: "kurta-saanjh",
      slug: "saanjh-kurta-set",
      name: "Saanjh",
      fullName: "Saanjh Kurta Set",
      subtitle: "Mulmul cotton, 3-piece",
      collection: "Kurta Sets",
      collectionSlug: "kurta-sets",
      price: 2890,
      compareAt: 3400,
      currency: "₹",
      colors: [
        { name: "Terracotta", hex: "#B7472A", weave: "plain" },
        { name: "Sage", hex: "#7A8761", weave: "plain" },
        { name: "Ivory", hex: "#E8DDC4", weave: "plain" },
      ],
      tags: ["new"],
      fabric: {
        gsm: 120,
        blend: "100% mulmul cotton",
        weave: "Plain weave, double-layered",
        weaveKey: "plain",
        fitType: "Relaxed",
        washCare: "Hand wash cold, line dry in shade",
        opacity: "Light · semi-opaque",
        breath: "High breathability",
      },
      model: { height: "5'7\"", size: "S", bust: 34, waist: 28, fitNote: "True to size" },
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      stockBySize: { XS: 4, S: 12, M: 8, L: 5, XL: 2, XXL: 0 },
      rating: 4.7,
      reviewCount: 142,
      fitFeedback: { runsTrue: 78, sizeUp: 12, sizeDown: 10 },
      description:
        "Hand-block-printed mulmul kurta with cigarette pants and a soft dupatta. Cut for movement; finished by hand at the hem.",
      pieces: ["Kurta", "Cigarette pants", "Mulmul dupatta"],
    },
    {
      id: "kurta-roohi",
      slug: "roohi-three-piece",
      name: "Roohi",
      fullName: "Roohi 3-Piece Set",
      subtitle: "Cotton-modal, wide-leg",
      collection: "3-Piece Kurta Sets",
      collectionSlug: "kurta-sets",
      price: 3490,
      currency: "₹",
      colors: [
        { name: "Sage", hex: "#7A8761", weave: "satin" },
        { name: "Wine", hex: "#6B2F3D", weave: "satin" },
      ],
      tags: ["bestseller"],
      fabric: {
        gsm: 145,
        blend: "70% cotton · 30% modal",
        weave: "Satin weave",
        weaveKey: "satin",
        fitType: "Regular",
        washCare: "Machine wash cold, gentle",
        opacity: "Medium",
        breath: "Medium breathability",
      },
      model: { height: "5'8\"", size: "M", bust: 36, waist: 29, fitNote: "True to size" },
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      stockBySize: { XS: 2, S: 8, M: 14, L: 9, XL: 4, XXL: 1 },
      rating: 4.8,
      reviewCount: 218,
      fitFeedback: { runsTrue: 85, sizeUp: 8, sizeDown: 7 },
      description:
        "A workhorse 3-piece in our breathable cotton-modal blend. Wide-leg pants, structured kurta, soft dupatta.",
      pieces: ["Structured kurta", "Wide-leg pants", "Soft dupatta"],
    },
    {
      id: "coord-amba",
      slug: "amba-coord-set",
      name: "Amba",
      fullName: "Amba Co-ord Set",
      subtitle: "Twill viscose, cropped",
      collection: "Co-ord Sets",
      collectionSlug: "co-ord-sets",
      price: 3290,
      currency: "₹",
      colors: [
        { name: "Cream", hex: "#E5DDC8", weave: "twill" },
        { name: "Charcoal", hex: "#2C2826", weave: "twill" },
      ],
      tags: ["new"],
      fabric: {
        gsm: 160,
        blend: "60% viscose · 40% cotton",
        weave: "Twill",
        weaveKey: "twill",
        fitType: "Relaxed",
        washCare: "Dry clean recommended",
        opacity: "Opaque",
        breath: "Medium",
      },
      model: { height: "5'6\"", size: "S", bust: 33, waist: 27, fitNote: "Runs slightly oversized" },
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      stockBySize: { XS: 5, S: 6, M: 10, L: 4, XL: 2, XXL: 0 },
      rating: 4.6,
      reviewCount: 89,
      fitFeedback: { runsTrue: 65, sizeUp: 25, sizeDown: 10 },
      description:
        "A modern co-ord in twill viscose — relaxed silhouette, hidden side pockets, mother-of-pearl buttons.",
      pieces: ["Cropped jacket", "Wide pants"],
    },
    {
      id: "kurta-noor",
      slug: "noor-kurta-set",
      name: "Noor",
      fullName: "Noor Kurta Set",
      subtitle: "Cotton voile, chikankari-inspired",
      collection: "Kurta Sets",
      collectionSlug: "kurta-sets",
      price: 2490,
      currency: "₹",
      colors: [
        { name: "Ivory", hex: "#FCFAF4", weave: "voile" },
        { name: "Powder", hex: "#D9C5C1", weave: "voile" },
      ],
      tags: ["bestseller"],
      fabric: {
        gsm: 110,
        blend: "100% cotton voile",
        weave: "Plain",
        weaveKey: "voile",
        fitType: "Regular",
        washCare: "Hand wash cold",
        opacity: "Sheer · lined",
        breath: "Very high",
      },
      model: { height: "5'6\"", size: "S", bust: 33, waist: 27, fitNote: "True to size" },
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      stockBySize: { XS: 6, S: 9, M: 11, L: 7, XL: 3, XXL: 1 },
      rating: 4.7,
      reviewCount: 176,
      fitFeedback: { runsTrue: 82, sizeUp: 9, sizeDown: 9 },
      description: "Featherweight cotton voile with hand-finished embroidery at the neckline and cuffs.",
      pieces: ["Embroidered kurta", "Straight pants", "Voile dupatta"],
    },
    {
      id: "coord-bageecha",
      slug: "bageecha-coord",
      name: "Bageecha",
      fullName: "Bageecha Co-ord",
      subtitle: "Block-print cotton",
      collection: "Co-ord Sets",
      collectionSlug: "co-ord-sets",
      price: 2790,
      currency: "₹",
      colors: [
        { name: "Olive", hex: "#7A8761", weave: "blockprint" },
        { name: "Terracotta", hex: "#B7472A", weave: "blockprint" },
      ],
      tags: ["new"],
      fabric: { gsm: 125, blend: "100% cotton", weave: "Plain · block-print", weaveKey: "blockprint", fitType: "Relaxed", washCare: "Machine wash cold", opacity: "Medium", breath: "High" },
      model: { height: "5'7\"", size: "M", bust: 35, waist: 28, fitNote: "True to size" },
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      stockBySize: { XS: 3, S: 7, M: 5, L: 6, XL: 2, XXL: 0 },
      rating: 4.5,
      reviewCount: 92,
      fitFeedback: { runsTrue: 70, sizeUp: 20, sizeDown: 10 },
      description: "A garden in block print. Soft cotton, hand-knotted ties at the waist.",
      pieces: ["Tie-front top", "Wide pants"],
    },
    {
      id: "kurta-mehfil",
      slug: "mehfil-kurta",
      name: "Mehfil",
      fullName: "Mehfil Kurta Set",
      subtitle: "Silk-cotton dobby",
      collection: "Kurta Sets",
      collectionSlug: "kurta-sets",
      price: 4290,
      currency: "₹",
      colors: [
        { name: "Gold", hex: "#B08947", weave: "dobby" },
        { name: "Wine", hex: "#6B2F3D", weave: "dobby" },
      ],
      tags: ["festive"],
      fabric: { gsm: 180, blend: "Silk-cotton blend", weave: "Dobby", weaveKey: "dobby", fitType: "Regular", washCare: "Dry clean only", opacity: "Opaque", breath: "Medium" },
      model: { height: "5'7\"", size: "S", bust: 34, waist: 28, fitNote: "True to size" },
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      stockBySize: { XS: 3, S: 6, M: 8, L: 4, XL: 1, XXL: 0 },
      rating: 4.9,
      reviewCount: 64,
      fitFeedback: { runsTrue: 90, sizeUp: 5, sizeDown: 5 },
      description: "A festive kurta woven in silk-cotton dobby — subtle texture, soft sheen.",
      pieces: ["Dobby kurta", "Silk-cotton pants", "Tassel dupatta"],
    },
  ];

  const REVIEWS = [
    { name: "Ananya M.", city: "Bengaluru", size: "S", rating: 5, daysAgo: 4, fit: "Runs true", body: "The mulmul is so soft, exactly like the photos. Wore it to a Diwali brunch — got asked five times where it's from.", photos: 2, verified: true },
    { name: "Priya R.", city: "Mumbai", size: "M", rating: 5, daysAgo: 11, fit: "Runs true", body: "Finally a brand that tells you the GSM. The fabric is breathable, the fit is honest. Exchange was painless when I wanted L.", photos: 1, verified: true },
    { name: "Sneha K.", city: "Pune", size: "L", rating: 4, daysAgo: 22, fit: "Size up", body: "Beautiful kurta, the print is exactly as shown. Slightly snug at bust — sizing up worked perfectly. Will repurchase.", photos: 0, verified: true },
    { name: "Aarti S.", city: "Delhi", size: "S", rating: 5, daysAgo: 8, fit: "Runs true", body: "Photographer kept commenting on how well-made it is. The hem stitching is impeccable.", photos: 3, verified: true },
    { name: "Ritika J.", city: "Hyderabad", size: "M", rating: 5, daysAgo: 15, fit: "Runs true", body: "Easy 5 stars. The fit guide is spot on — measure once, buy with confidence.", photos: 1, verified: true },
    { name: "Meera V.", city: "Chennai", size: "XL", rating: 4, daysAgo: 30, fit: "Runs true", body: "Comfortable for long workdays. Wish the dupatta were a touch longer but the kurta itself is wonderful.", photos: 0, verified: true },
  ];

  const COLLECTIONS = [
    {
      slug: "kurta-sets",
      name: "Kurta Sets",
      tagline: "Three pieces, every day",
      blurb: "Kurta, pants, and dupatta — cut for movement, finished by hand at the hem.",
      coverColor: "#B7472A",
      coverWeave: "plain",
      coverName: "Saanjh",
      coverGsm: 120,
      count: 38,
    },
    {
      slug: "co-ord-sets",
      name: "Co-ord Sets",
      tagline: "Two pieces, one story",
      blurb: "Cropped jackets, wide pants, matching tops and bottoms made to be worn together — or apart.",
      coverColor: "#7A8761",
      coverWeave: "twill",
      coverName: "Amba",
      coverGsm: 160,
      count: 24,
    },
    {
      slug: "festive",
      name: "Festive Edit",
      tagline: "For the days that ask to be remembered",
      blurb: "Silk-cotton dobby, hand-finished tassel work, gold thread. Made to be photographed in.",
      coverColor: "#B08947",
      coverWeave: "dobby",
      coverName: "Mehfil",
      coverGsm: 180,
      count: 12,
    },
  ];

  const TRUST_ITEMS = [
    { text: "Size-true · cousin-verified measurements" },
    { text: "Made in Surat, Gujarat" },
    { text: "Free exchange on your first order" },
    { text: "100% Indian-sourced fabric" },
    { text: "What you see is what arrives" },
    { text: "Pick up from us in Surat — save ₹50" },
  ];

  const PINCODE_DELIVERY = {
    "395": { city: "Surat", days: [1, 2], pickup: true },
    "400": { city: "Mumbai", days: [3, 4] },
    "560": { city: "Bengaluru", days: [4, 5] },
    "110": { city: "Delhi", days: [4, 6] },
    "600": { city: "Chennai", days: [5, 6] },
    "700": { city: "Kolkata", days: [5, 7] },
    "411": { city: "Pune", days: [3, 5] },
    "500": { city: "Hyderabad", days: [4, 6] },
    "380": { city: "Ahmedabad", days: [2, 3] },
    "302": { city: "Jaipur", days: [3, 5] },
  };

  const SIZE_CHART = {
    headers: ["Size", "Bust (in)", "Waist (in)", "Hip (in)", "Length (in)"],
    rows: [
      ["XS", "32", "26", "34", "42"],
      ["S",  "34", "28", "36", "42"],
      ["M",  "36", "30", "38", "43"],
      ["L",  "38", "32", "40", "43"],
      ["XL", "40", "34", "42", "44"],
      ["XXL","42", "36", "44", "44"],
    ],
  };

  return { PRODUCTS, REVIEWS, COLLECTIONS, TRUST_ITEMS, PINCODE_DELIVERY, SIZE_CHART };
})();
